/* Official SEC facts only. Missing fields are null; no invented scores or bottlenecks. */
const fs=require('fs');
const now=new Date(),month=now.toLocaleDateString('sv-SE',{timeZone:'Asia/Seoul'}).slice(0,7),file='monthly-review.json';
const previous=fs.existsSync(file)?JSON.parse(fs.readFileSync(file)):null;
const report={version:'2.1',month,retrievedAt:now.toISOString(),status:'collecting',scope:'기존 레이더 + 미국 기본 관심종목. 전 시장 발굴 아님.',rule:'연간 매출 전년 대비 25% 이상 증가한 기업은 추가 검토 후보. 설정된 탐색 조건이며 텐배거 확률이나 편입 확정 아님.',companies:[],newCandidates:[],errors:[],limitations:['병목·경쟁력·정책·밸류에이션·경영진 실행력은 공시 본문 검토 필요. 자동 판정하지 않음.','Investment 점수 및 편입·탈락은 본 수집 작업으로 변경하지 않음.','연간 지표는 보고 지연이 있으며 분기 추세와 다를 수 있음.']};
async function get(url){const r=await fetch(url,{headers:{'User-Agent':'TenbaggerRadar research contact https://github.com/jredwin-lang/TenbaggerRadar','Accept':'application/json'},signal:AbortSignal.timeout(20000)});if(!r.ok)throw Error('HTTP '+r.status);return r.json()}
function annual(facts,tags,unit='USD'){for(const tag of tags){const rows=facts['us-gaap']?.[tag]?.units?.[unit];if(!rows)continue;const valid=rows.filter(r=>['10-K','10-K/A'].includes(r.form)&&r.start&&r.end&&Number.isFinite(r.val)&&Date.parse(r.end)-Date.parse(r.start)>=330*86400000&&Date.parse(r.end)-Date.parse(r.start)<=380*86400000);const by=new Map();for(const r of valid.sort((a,b)=>a.filed.localeCompare(b.filed)))by.set(r.end,r);const sorted=[...by.values()].sort((a,b)=>b.end.localeCompare(a.end));if(sorted.length)return {tag,unit,latest:sorted[0],prior:sorted.find(r=>Date.parse(sorted[0].end)-Date.parse(r.end)>300*86400000)}}return null}
function point(facts,tags){for(const tag of tags){const rows=facts['us-gaap']?.[tag]?.units?.USD?.filter(r=>!r.start&&Number.isFinite(r.val));if(rows?.length)return {tag,unit:'USD',latest:rows.sort((a,b)=>b.end.localeCompare(a.end)||b.filed.localeCompare(a.filed))[0]}}return null}
async function main(){fs.mkdirSync('monthly-history',{recursive:true});const market=JSON.parse(fs.readFileSync('market.json')),inputs=JSON.parse(fs.readFileSync('inputs.json'));let map;try{map=Object.values(await get('https://www.sec.gov/files/company_tickers.json'))}catch(e){report.errors.push({item:'SEC 회사 코드 목록',message:e.message});report.status='unavailable';}
if(map){const tickers=[...new Set([...inputs.data.map(s=>s.ticker),...market.us.filter(s=>s.watchDefault).map(s=>s.symbol)])];for(const ticker of tickers){const company=map.find(s=>s.ticker===ticker),original=inputs.data.find(s=>s.ticker===ticker),entry={ticker,name:market.us.find(s=>s.symbol===ticker)?.name||original?.name||ticker,original:!!original,investment:original?.investment??null,status:'검토 필요',change:'초회 기준선',source:null};try{if(!company)throw Error('SEC CIK 매칭 확인 불가');const cik=String(company.cik_str).padStart(10,'0'),url='https://data.sec.gov/api/xbrl/companyfacts/CIK'+cik+'.json',facts=await get(url),sub=await get('https://data.sec.gov/submissions/CIK'+cik+'.json');entry.source=url;entry.revenue=annual(facts.facts,['RevenueFromContractWithCustomerExcludingAssessedTax','Revenues','SalesRevenueNet']);entry.netIncome=annual(facts.facts,['NetIncomeLoss','ProfitLoss']);entry.operatingCash=annual(facts.facts,['NetCashProvidedByUsedInOperatingActivities']);entry.capex=annual(facts.facts,['PaymentsToAcquirePropertyPlantAndEquipment']);entry.cash=point(facts.facts,['CashAndCashEquivalentsAtCarryingValue']);entry.revenueGrowth=entry.revenue?.prior&&entry.revenue.prior.val>0?(entry.revenue.latest.val/entry.revenue.prior.val-1)*100:null;entry.fcf=entry.operatingCash&&entry.capex&&entry.operatingCash.latest.start===entry.capex.latest.start&&entry.operatingCash.latest.end===entry.capex.latest.end?entry.operatingCash.latest.val-entry.capex.latest.val:null;const recent=sub.filings?.recent;entry.filings=recent?recent.form.map((form,i)=>({form,date:recent.filingDate[i],url:'https://www.sec.gov/Archives/edgar/data/'+Number(cik)+'/'+recent.accessionNumber[i].replaceAll('-','')+'/'+recent.primaryDocument[i]})).filter(r=>r.date>=month+'-01'||['10-K','10-Q'].includes(r.form)).slice(0,8):[];const old=previous?.companies?.find(s=>s.ticker===ticker);if(old)entry.change=JSON.stringify([entry.revenue,entry.netIncome,entry.operatingCash,entry.capex,entry.cash,entry.filings])===JSON.stringify([old.revenue,old.netIncome,old.operatingCash,old.capex,old.cash,old.filings])?'収集範囲内の変更なし':'재무·공시 변화 발견';entry.change=entry.change.replace('収集範囲内の変更なし','수집 범위 내 변화 없음');if(!original&&entry.revenueGrowth>=25)report.newCandidates.push({ticker,name:entry.name,revenueGrowth:entry.revenueGrowth,source:url,status:'추가 검토 후보 · 편입 미확정'});entry.status=entry.change==='재무·공시 변화 발견'?'변화 재검토':'사업 논리 재검토 필요';}catch(e){entry.status='확인 불가';entry.error=e.message;report.errors.push({item:ticker,message:e.message})}report.companies.push(entry)}}
report.status=report.companies.some(s=>s.source)?(report.errors.length?'partial':'verified'):'unavailable';report.newCandidates.sort((a,b)=>b.revenueGrowth-a.revenueGrowth);fs.writeFileSync(file,JSON.stringify(report));fs.writeFileSync('monthly-history/'+month+'-'+now.toISOString().replace(/[:.]/g,'-')+'.json',JSON.stringify(report));console.log(JSON.stringify({month,status:report.status,companies:report.companies.length,verified:report.companies.filter(s=>s.source).length,candidates:report.newCandidates.length,errors:report.errors.slice(0,3)}));}
main().catch(e=>{console.error(e);process.exit(1)});
